#pragma once
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "console.h"
#include <windows.h>
#include "narrative.h"
#include "eventhandler.h"
#include "console.h"
void dialoguePerson0();
void dialoguePerson1();
void dialoguePerson2();
void dialoguePerson3();
